# Alacritty Configuration file
#
[general]
import = ["~/.config/alacritty/themes/tokyonight_storm.toml"]

# Terminal
[env]
term = "xterm-256color"

# Windows specific configuration
[window]
dynamic_title = false
decorations_theme_variant = "Dark"
padding = { x = 10}

# Font Configuration
[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style="Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style="Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style="Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style="Bold Italic" }
size = 11.0
offset = { y = 5 }


# Cursor Settings
[cursor]
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 400

# Mouse Settings
[mouse]
hide_when_typing = true

# Keybindings
[keyboard]
bindings = [{ key = "F11", action = "ToggleFullScreen"}]

